translate_to_english_task:
  description: >
    Translate {topic} to english ONLY if its in different language or not in english or a mix of different language and 
    english. Make bullet form format:
    1. English translation
    2. Original text
  expected_output: >
    Make bullet form of translation of english version and original text.
  agent: agent2

make_conversation_task:
  description: >
    Make a conversation based on the bullet text. if it has parenthesis, do the same format as that.
  expected_output: >
    Reply a most likely conversation like a multi turn communication. dont change the format of
  agent:

final_task:
  description: >
    Make a conversation based on the text given. if it has parenthesis, do the same format as that.
  expected_output: >
    Reply a most likely conversation like a multi turn communication. dont change the format of
  agent: