entry_task:
  description: >
    Have a conversation about {topic} or talk about {topic}
  expected_output: >
    have a normal conversation based on {topic}. not more than 5 sentences and full of
    explanation. minimum of 1 sentence to 4 sentences.
  agent: identity_agent



